### PR TITLE
fix(prop-types): use proptypes from a different package rather than f…

### PR DESCRIPTION
**Pull request by nicubarbaros**
Add PropTypes in order to avoid React 15 warning.

### CODE REVIEW

**Comment by benwiley4000** [comment]
Awesome thanks!

**Comment by nicubarbaros** [comment]
Cheers!

**Comment by benwiley4000** [comment]
@nicubarbaros I just noticed this (my bad for not catching it), but I'd prefer you not correct "linting errors" like quote style and function spacing - it adds a whole bunch of noise to the diff, and it's not what I wanted either! :wink:

**Comment by nicubarbaros** [comment]
@benwiley4000 I am very sorry. ;(

**Comment by benwiley4000** [comment]
@nicubarbaros hey don't worry about it! I thought it was good enough to merge. :)

I just thought I would let you know for future reference - concise PRs will make open source maintainers happy. :D

**Comment by benwiley4000** [comment]
And thanks again for the contribution :)

**Pull request merged**
