### PR TITLE
Correct main script

### LINKED ISSUE #10: NPM tarball doesn't contain dist/index.js
I tried to install and use react-gif-player today but the `dist/index.js` is missing in NPM tarball, making the module not available in the application as it's the main file of the lib.

Actual content of the tarball:

```
-rw-rw-r-- 1000/1000      1470 2016-11-25 04:35 package/package.json
-rw-rw-r-- 1000/1000        85 2016-11-25 04:34 package/.npmignore
-rw-rw-r-- 1000/1000      4148 2016-11-25 04:35 package/README.md
-rw-rw-r-- 1000/1000      1076 2016-11-25 04:34 package/LICENSE
-rw-rw-r-- 1000/1000      1144 2016-11-25 04:34 package/webpack.config.js
-rw-rw-r-- 1000/1000      1075 2016-11-25 04:34 package/devServer.js
-rw-rw-r-- 1000/1000        84 2016-11-25 04:34 package/.babelrc
-rw-rw-r-- 1000/1000       559 2016-11-25 04:34 package/src/GifPlayer.js
-rw-rw-r-- 1000/1000      2057 2016-11-25 04:34 package/src/index.js
-rw-rw-r-- 1000/1000      2332 2016-11-25 04:34 package/src/GifPlayer.scss
-rw-rw-r-- 1000/1000       614 2016-11-25 04:34 package/CONTRIBUTING.md
-rw-rw-r-- 1000/1000     10261 2016-11-25 04:32 package/dist/gifplayer.js
-rw-rw-r-- 1000/1000      1444 2016-11-25 04:32 package/dist/gifplayer.css
```

I hope you'll be able to fix this quickly :)

### PR DESCRIPTION
**Pull request by GauthierPLM**
Fix #10

### CODE REVIEW

**Comment by benwiley4000** [comment]
Looks good to me. Thanks for getting this!

**Comment by benwiley4000** [comment]
@Kendos-Kenlen could you try v0.2.2 from npm and verify it works?

**Comment by GauthierPLM** [comment]
Yeap it works, the module is well imported.

Just a little question : the gif round button is automatically added to the preview image or we have to add it manually ?
I visited your website and it appear on your gifs, but not in mine.

**Comment by benwiley4000** [comment]
@Kendos-Kenlen did you include the CSS sheet from the module dist directory in your page?

**Comment by GauthierPLM** [comment]
Ah nop, sorry ... Thanks !

**Pull request merged**
