### PR TITLE
webpack umd globalObject fix

### LINKED ISSUE #30: Webpack UMD target issue
ReferenceError: window is not defined
    at Object.<anonymous> (/app/node_modules/react-gif-player/dist/gifplayer.js:10:4)

I think this is relevant -
https://medium.com/@JakeXiao/window-is-undefined-in-umd-library-output-for-webpack4-858af1b881df

### PR DESCRIPTION
**Pull request by mohitmayank**
Fixes https://github.com/benwiley4000/react-gif-player/issues/30

### CODE REVIEW

**Comment by benwiley4000** [comment]
@mohitmayank sorry, just now getting to this! Thanks for the fix. On another project we did this: https://github.com/benwiley4000/cassette/blob/872e5960ed77e001961b89699f32aa8b3c98fc9e/getPackageWebpackConfig.js#L108

Would that work ok? I might be more comfortable with that as the fix since I know it works.

**Comment by benwiley4000** [comment]
@mohitmayank could you let me know what you think?

**Comment by eg9y** [comment]
stumbled on this issue as well. Would be cool if this gets merged :)

**Comment by mohitmayank** [comment]
@benwiley4000 i just realised that this this got missed by me. Fix you mentioned should also fix this.

**Comment by benwiley4000** [comment]
Let's keep the PR open just so I don't forget to address it - my backlog has been a bit crowded. I'll try to get to it in the next several days if time permits, or feel free to make a new PR! Thanks

**Comment by mohitmayank** [comment]
Superseded by https://github.com/benwiley4000/react-gif-player/pull/33

**Pull request closed without merging**
